name: Aggregate metriq-data (PR)

on:
  pull_request:
    paths:
      - '*/v*/**/results.json'
      - 'scripts/aggregate.py'
  workflow_dispatch:

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Run ETL
        run: |
          python scripts/aggregate.py

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: aggregated-dist
          path: dist
          if-no-files-found: warn
